version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: mysql80
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: db_lamp
      MYSQL_USER: lamp_user
      MYSQL_PASSWORD: lamp_pass
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     PMA_ARBITRARY: 1
     MYSQL_ROOT_PASSWORD: my-secret-pw
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions